-- =============================================================================
-- DI CHIES — Catalogue seed from Lovable repo (di-chies-marketplace)
-- Source: supabase/migrations/20260813170935_58d9f572-e08e-407d-9753-76f055cf4d4f.sql
--
-- HOW TO USE
-- 1. Make sure your schema is already applied (run supabase-schema.sql first).
-- 2. Open Supabase Dashboard → SQL Editor → New query.
-- 3. Paste this entire file and Run.
--
-- This will TRUNCATE existing catalogue data (categories, subcategories,
-- products, promotions, booking_items, bookings) then insert Lovable’s data:
--   • 13 categories
--   • ~40 subcategories
--   • ~200 products (Nigerian supermarket assortment)
--   • 4 promotions
-- =============================================================================

-- Clear existing catalogue (safe on empty project)
TRUNCATE public.booking_items, public.bookings, public.products, public.subcategories, public.categories, public.promotions RESTART IDENTITY CASCADE;

INSERT INTO public.categories (name, slug, description, sort_order, age_restricted) VALUES
('Food Stuff & Groceries','food-groceries','Staples, grains, oils, spices and everyday cooking essentials.',1,false),
('Drinks & Beverages','drinks-beverages','Water, soft drinks, juices, malt, milk, tea and coffee.',2,false),
('Biscuits & Snacks','biscuits-snacks','Biscuits, cookies, chocolate, nuts, cereals and packaged treats.',3,false),
('Premium Wines & Spirits','premium-wines','A curated cellar of wines, champagne and premium beverages.',4,true),
('Baby & Kids','baby-kids','Feeding, care and everyday essentials for babies and children.',5,false),
('Beauty & Cosmetics','beauty-cosmetics','Skincare, fragrance, makeup and haircare.',6,false),
('Household Essentials','household-essentials','Cleaning tools, storage and everyday home items.',7,false),
('Personal Care','personal-care','Oral care, bath, shaving and hygiene products.',8,false),
('Laundry & Cleaning','laundry-cleaning','Detergents, softeners, disinfectants and cleaning chemicals.',9,false),
('Kitchen & Dining','kitchen-dining','Cookware, tableware, cutlery and food storage.',10,false),
('Books, Stationery & School','books-stationery','Exercise books, pens, art supplies and school essentials.',11,false),
('Electronics & Accessories','electronics-accessories','Batteries, bulbs, chargers and small home electronics.',12,false),
('Pet Supplies','pet-supplies','Food, care and accessories for pets.',13,false);

UPDATE public.categories SET image_url = 'https://placehold.co/1200x800/e7e7e9/18181b?text=' || replace(name,' ','+');

INSERT INTO public.subcategories (category_id, name, slug, sort_order)
SELECT c.id, s.name, s.slug, s.ord FROM (VALUES
('food-groceries','Grains & Rice','grains-rice',1),
('food-groceries','Oils & Fats','oils-fats',2),
('food-groceries','Pasta & Noodles','pasta-noodles',3),
('food-groceries','Spices & Seasoning','spices-seasoning',4),
('food-groceries','Canned & Packaged','canned-packaged',5),
('food-groceries','Fresh Produce','fresh-produce',6),
('drinks-beverages','Water & Soft Drinks','water-soft-drinks',1),
('drinks-beverages','Juices & Malt','juices-malt',2),
('drinks-beverages','Dairy & Yoghurt','dairy-yoghurt',3),
('drinks-beverages','Tea & Coffee','tea-coffee',4),
('biscuits-snacks','Biscuits & Cookies','biscuits-cookies',1),
('biscuits-snacks','Chocolate & Candy','chocolate-candy',2),
('biscuits-snacks','Nuts & Savoury','nuts-savoury',3),
('biscuits-snacks','Cereals & Bars','cereals-bars',4),
('premium-wines','Red Wine','red-wine',1),
('premium-wines','White & Rose','white-rose',2),
('premium-wines','Sparkling & Champagne','sparkling-champagne',3),
('baby-kids','Feeding','feeding',1),
('baby-kids','Diapers & Wipes','diapers-wipes',2),
('baby-kids','Baby Care','baby-care',3),
('beauty-cosmetics','Skincare','skincare',1),
('beauty-cosmetics','Fragrance','fragrance',2),
('beauty-cosmetics','Makeup','makeup',3),
('beauty-cosmetics','Hair Care','hair-care',4),
('household-essentials','Cleaning Tools','cleaning-tools',1),
('household-essentials','Storage & Organisation','storage',2),
('household-essentials','Paper & Disposables','paper-disposables',3),
('personal-care','Oral Care','oral-care',1),
('personal-care','Bath & Body','bath-body',2),
('personal-care','Shaving & Hygiene','shaving-hygiene',3),
('laundry-cleaning','Detergents','detergents',1),
('laundry-cleaning','Disinfectants','disinfectants',2),
('kitchen-dining','Cookware','cookware',1),
('kitchen-dining','Tableware','tableware',2),
('kitchen-dining','Food Storage','food-storage',3),
('books-stationery','Exercise Books','exercise-books',1),
('books-stationery','Writing & Art','writing-art',2),
('books-stationery','School Accessories','school-accessories',3),
('electronics-accessories','Power & Batteries','power-batteries',1),
('electronics-accessories','Lighting','lighting',2),
('pet-supplies','Pet Food','pet-food',1),
('pet-supplies','Pet Care','pet-care',2)
) AS s(cat, name, slug, ord)
JOIN public.categories c ON c.slug = s.cat;

INSERT INTO public.products (name, slug, description, category_id, subcategory_id, brand, price, unit, stock_quantity, tags)
SELECT p.name,
       trim(both '-' from lower(regexp_replace(p.name,'[^a-zA-Z0-9]+','-','g'))),
       'Quality ' || p.name || ' available at DI CHIES. Reserve online and collect in store.',
       c.id,
       sc.id,
       p.brand,
       p.price,
       p.unit,
       p.stock,
       string_to_array(p.tags, ',')
FROM (VALUES
('Royal Stallion Parboiled Rice 50kg','food-groceries','grains-rice','Royal Stallion',92000,'bag',40,'rice,staple,grains'),
('Mama Gold Parboiled Rice 25kg','food-groceries','grains-rice','Mama Gold',47500,'bag',60,'rice,staple'),
('Caprice Rice 5kg','food-groceries','grains-rice','Caprice',11500,'bag',120,'rice'),
('Basmati Long Grain Rice 5kg','food-groceries','grains-rice','Tilda',18500,'bag',45,'rice,premium'),
('Honey Beans (Oloyin) 5kg','food-groceries','grains-rice','DI CHIES Farms',13800,'bag',80,'beans,protein'),
('Brown Beans 2kg','food-groceries','grains-rice','DI CHIES Farms',5900,'bag',95,'beans'),
('White Garri (Ijebu) 4kg','food-groceries','grains-rice','Ijebu Choice',5200,'bag',110,'garri,staple'),
('Yellow Garri 4kg','food-groceries','grains-rice','Ijebu Choice',5600,'bag',90,'garri'),
('Golden Penny Semovita 2kg','food-groceries','grains-rice','Golden Penny',5400,'pack',140,'semolina,swallow'),
('Ayoola Poundo Yam Flour 1.8kg','food-groceries','grains-rice','Ayoola',6200,'pack',85,'yam,swallow'),
('Golden Penny Prime Flour 2kg','food-groceries','grains-rice','Golden Penny',4300,'pack',130,'flour,baking'),
('Wheat Flour 1kg','food-groceries','grains-rice','Dangote',2100,'pack',160,'flour'),
('Devon King Cooking Oil 3.5L','food-groceries','oils-fats','Devon King',13400,'bottle',70,'oil,cooking'),
('Kings Vegetable Oil 5L','food-groceries','oils-fats','Kings',19800,'bottle',55,'oil,vegetable'),
('Pure Palm Oil 4L','food-groceries','oils-fats','DI CHIES Farms',12500,'bottle',65,'palm oil,oil'),
('Extra Virgin Olive Oil 500ml','food-groceries','oils-fats','Bertolli',14200,'bottle',40,'olive oil,premium'),
('Groundnut Oil 2L','food-groceries','oils-fats','Grand',9600,'bottle',75,'oil'),
('Golden Penny Spaghetti 500g','food-groceries','pasta-noodles','Golden Penny',1250,'pack',300,'pasta,spaghetti'),
('Power Pasta Macaroni 500g','food-groceries','pasta-noodles','Power',1180,'pack',240,'pasta,macaroni'),
('Indomie Chicken Noodles Carton (40)','food-groceries','pasta-noodles','Indomie',15900,'carton',50,'noodles,carton'),
('Indomie Onion Chicken Pack of 5','food-groceries','pasta-noodles','Indomie',2100,'pack',200,'noodles'),
('Honeywell Wheat Semolina 1kg','food-groceries','pasta-noodles','Honeywell',3100,'pack',120,'semolina'),
('Maggi Star Seasoning Cubes 100s','food-groceries','spices-seasoning','Maggi',2450,'pack',260,'seasoning,cubes'),
('Knorr Chicken Cubes 50s','food-groceries','spices-seasoning','Knorr',1780,'pack',220,'seasoning'),
('Curry Powder 100g','food-groceries','spices-seasoning','Ducros',1150,'pack',180,'spice,curry'),
('Dried Thyme 50g','food-groceries','spices-seasoning','Ducros',980,'pack',175,'spice,thyme'),
('Iodised Table Salt 1kg','food-groceries','spices-seasoning','Dangote',850,'pack',300,'salt'),
('Granulated Sugar 1kg','food-groceries','spices-seasoning','Dangote',2350,'pack',280,'sugar'),
('Ground Crayfish 200g','food-groceries','spices-seasoning','DI CHIES Kitchen',3400,'pack',90,'crayfish,seasoning'),
('Suya Spice Mix 150g','food-groceries','spices-seasoning','DI CHIES Kitchen',1900,'pack',110,'spice,suya'),
('Gino Tomato Paste 210g','food-groceries','canned-packaged','Gino',1350,'piece',320,'tomato,canned'),
('Sonia Tomato Paste Sachet 70g','food-groceries','canned-packaged','Sonia',420,'piece',500,'tomato'),
('Titus Sardines 125g','food-groceries','canned-packaged','Titus',2350,'piece',260,'fish,canned'),
('Baked Beans in Tomato Sauce 400g','food-groceries','canned-packaged','Heinz',2100,'piece',180,'beans,canned'),
('Sweet Corn Tin 340g','food-groceries','canned-packaged','Green Giant',2400,'piece',150,'corn,canned'),
('Peak Evaporated Milk 170g','food-groceries','canned-packaged','Peak',1250,'piece',300,'milk,canned'),
('Fresh Tomatoes 1kg','food-groceries','fresh-produce','DI CHIES Farms',3200,'kg',70,'fresh,vegetable'),
('Red Onions 1kg','food-groceries','fresh-produce','DI CHIES Farms',2600,'kg',85,'fresh,vegetable'),
('Scotch Bonnet Pepper 500g','food-groceries','fresh-produce','DI CHIES Farms',2900,'pack',60,'fresh,pepper'),
('Irish Potatoes 2kg','food-groceries','fresh-produce','DI CHIES Farms',5400,'bag',55,'fresh,potato'),
('Sweet Potatoes 2kg','food-groceries','fresh-produce','DI CHIES Farms',4300,'bag',50,'fresh,potato'),
('Puna Yam Tuber (Large)','food-groceries','fresh-produce','DI CHIES Farms',7800,'piece',40,'fresh,yam'),
('Crate of Eggs (30)','food-groceries','fresh-produce','DI CHIES Farms',6800,'carton',65,'eggs,fresh'),
('Sliced Sandwich Bread 600g','food-groceries','fresh-produce','Butterfield',2200,'piece',90,'bread,bakery'),
('Frozen Chicken Drumsticks 1kg','food-groceries','canned-packaged','DI CHIES Frozen',8900,'kg',45,'frozen,chicken'),
('Frozen Titus Fish 1kg','food-groceries','canned-packaged','DI CHIES Frozen',7600,'kg',40,'frozen,fish'),
('Eva Table Water 75cl (Pack of 12)','drinks-beverages','water-soft-drinks','Eva',3600,'pack',180,'water'),
('Cway Bottled Water 1.5L','drinks-beverages','water-soft-drinks','Cway',850,'bottle',300,'water'),
('Coca-Cola 50cl PET (Pack of 12)','drinks-beverages','water-soft-drinks','Coca-Cola',7200,'pack',120,'soft drink,cola'),
('Fanta Orange 50cl PET','drinks-beverages','water-soft-drinks','Fanta',700,'bottle',280,'soft drink'),
('Sprite 50cl PET','drinks-beverages','water-soft-drinks','Sprite',700,'bottle',270,'soft drink'),
('Pepsi 1.5L','drinks-beverages','water-soft-drinks','Pepsi',1500,'bottle',150,'soft drink'),
('Schweppes Chapman 33cl Can','drinks-beverages','water-soft-drinks','Schweppes',900,'piece',200,'soft drink'),
('Chi Exotic Pineapple Juice 1L','drinks-beverages','juices-malt','Chi Exotic',2100,'bottle',140,'juice'),
('Five Alive Citrus Burst 1L','drinks-beverages','juices-malt','Five Alive',2050,'bottle',130,'juice'),
('Hollandia Orange Juice 1L','drinks-beverages','juices-malt','Hollandia',2250,'bottle',120,'juice'),
('Maltina Classic 33cl (Pack of 6)','drinks-beverages','juices-malt','Maltina',4200,'pack',110,'malt'),
('Amstel Malta 33cl Can','drinks-beverages','juices-malt','Amstel',800,'piece',220,'malt'),
('Lucozade Boost 33cl','drinks-beverages','juices-malt','Lucozade',1250,'bottle',160,'energy drink'),
('Red Bull Energy Drink 25cl','drinks-beverages','juices-malt','Red Bull',2300,'piece',140,'energy drink'),
('Peak Full Cream Milk Powder 900g','drinks-beverages','dairy-yoghurt','Peak',18500,'pack',70,'milk,dairy'),
('Dano Cool Cow Milk Powder 400g','drinks-beverages','dairy-yoghurt','Dano',6900,'pack',95,'milk'),
('Hollandia Evaporated Milk 1L','drinks-beverages','dairy-yoghurt','Hollandia',3100,'bottle',110,'milk'),
('Hollandia Yoghurt Strawberry 1L','drinks-beverages','dairy-yoghurt','Hollandia',3400,'bottle',80,'yoghurt'),
('Farm Fresh Greek Yoghurt 500ml','drinks-beverages','dairy-yoghurt','Farm Fresh',2900,'bottle',60,'yoghurt'),
('Lipton Yellow Label Tea 100 Bags','drinks-beverages','tea-coffee','Lipton',4600,'pack',90,'tea'),
('Top Tea Bags 50s','drinks-beverages','tea-coffee','Top Tea',2100,'pack',110,'tea'),
('Nescafe Classic Coffee 100g','drinks-beverages','tea-coffee','Nescafe',7400,'piece',85,'coffee'),
('Milo Chocolate Drink Refill 900g','drinks-beverages','tea-coffee','Milo',12200,'pack',75,'chocolate drink'),
('Bournvita Refill 500g','drinks-beverages','tea-coffee','Bournvita',6800,'pack',80,'chocolate drink'),
('Chateau Reserve Cabernet Sauvignon 75cl','premium-wines','red-wine','Chateau Reserve',28500,'bottle',35,'wine,red'),
('Barone Montepulciano d''Abruzzo 75cl','premium-wines','red-wine','Barone',24000,'bottle',30,'wine,red'),
('Four Cousins Sweet Red 75cl','premium-wines','red-wine','Four Cousins',16500,'bottle',48,'wine,red'),
('Carlo Rossi Sweet Red 75cl','premium-wines','red-wine','Carlo Rossi',15200,'bottle',52,'wine,red'),
('Nederburg Sauvignon Blanc 75cl','premium-wines','white-rose','Nederburg',22500,'bottle',28,'wine,white'),
('Robertson Chardonnay 75cl','premium-wines','white-rose','Robertson',21000,'bottle',26,'wine,white'),
('Provence Rose 75cl','premium-wines','white-rose','Maison Sud',26500,'bottle',22,'wine,rose'),
('Moet & Chandon Imperial Brut 75cl','premium-wines','sparkling-champagne','Moet & Chandon',148000,'bottle',12,'champagne,premium'),
('Veuve Clicquot Yellow Label 75cl','premium-wines','sparkling-champagne','Veuve Clicquot',165000,'bottle',8,'champagne,premium'),
('Martini Prosecco 75cl','premium-wines','sparkling-champagne','Martini',32000,'bottle',24,'sparkling'),
('Chamdor Sparkling Grape (Non-Alcoholic) 75cl','premium-wines','sparkling-champagne','Chamdor',9800,'bottle',40,'sparkling'),
('McVitie''s Digestive Biscuits 400g','biscuits-snacks','biscuits-cookies','McVitie''s',4200,'pack',140,'biscuits'),
('Oreo Chocolate Sandwich Cookies 133g','biscuits-snacks','biscuits-cookies','Oreo',1850,'pack',200,'cookies'),
('Cabin Biscuits Family Pack','biscuits-snacks','biscuits-cookies','Yale',1350,'pack',180,'biscuits'),
('Nutri-C Cream Crackers 200g','biscuits-snacks','biscuits-cookies','Nutri-C',1250,'pack',190,'crackers'),
('Loacker Hazelnut Wafers 175g','biscuits-snacks','biscuits-cookies','Loacker',4800,'pack',85,'wafers'),
('Butter Pound Cake 400g','biscuits-snacks','biscuits-cookies','DI CHIES Bakery',3600,'piece',60,'cake,bakery'),
('Cadbury Dairy Milk Chocolate 90g','biscuits-snacks','chocolate-candy','Cadbury',3200,'piece',150,'chocolate'),
('Snickers Chocolate Bar 50g','biscuits-snacks','chocolate-candy','Snickers',1250,'piece',220,'chocolate'),
('Ferrero Rocher 16 Pieces','biscuits-snacks','chocolate-candy','Ferrero',15800,'pack',45,'chocolate,gift'),
('Trebor Peppermint Rolls (Pack of 12)','biscuits-snacks','chocolate-candy','Trebor',1450,'pack',200,'candy'),
('Orbit Chewing Gum 14g','biscuits-snacks','chocolate-candy','Orbit',750,'pack',260,'gum'),
('Roasted Cashew Nuts 250g','biscuits-snacks','nuts-savoury','DI CHIES Kitchen',5400,'pack',95,'nuts'),
('Salted Groundnuts 400g','biscuits-snacks','nuts-savoury','DI CHIES Kitchen',2600,'pack',130,'nuts'),
('Pringles Original 165g','biscuits-snacks','nuts-savoury','Pringles',4300,'piece',110,'chips'),
('Microwave Popcorn 3 Pack','biscuits-snacks','nuts-savoury','Act II',2900,'pack',100,'popcorn'),
('Plantain Chips 150g','biscuits-snacks','nuts-savoury','DI CHIES Kitchen',1400,'pack',170,'chips,snack'),
('Kellogg''s Cornflakes 500g','biscuits-snacks','cereals-bars','Kellogg''s',7200,'pack',90,'cereal,breakfast'),
('Golden Morn Cereal 900g','biscuits-snacks','cereals-bars','Golden Morn',8600,'pack',85,'cereal,breakfast'),
('Quaker Oats 1kg','biscuits-snacks','cereals-bars','Quaker',9400,'pack',70,'oats,breakfast'),
('Nature Valley Granola Bars 5 Pack','biscuits-snacks','cereals-bars','Nature Valley',4900,'pack',75,'granola,bars'),
('NAN Optipro 1 Infant Formula 400g','baby-kids','feeding','NAN',14800,'pack',55,'baby,formula'),
('Cerelac Wheat & Milk 400g','baby-kids','feeding','Cerelac',7800,'pack',80,'baby,cereal'),
('Avent Anti-Colic Feeding Bottle 260ml','baby-kids','feeding','Philips Avent',12500,'piece',40,'baby,bottle'),
('Baby Weaning Bowl & Spoon Set','baby-kids','feeding','Nuby',6900,'pack',50,'baby,feeding'),
('Baby Sippy Cup 300ml','baby-kids','feeding','Nuby',4800,'piece',60,'baby,cup'),
('Pampers Baby Dry Medium (Pack of 62)','baby-kids','diapers-wipes','Pampers',18900,'pack',65,'diapers'),
('Huggies Ultra Comfort Large (Pack of 50)','baby-kids','diapers-wipes','Huggies',17500,'pack',58,'diapers'),
('Molfix Baby Wipes 120s','baby-kids','diapers-wipes','Molfix',3600,'pack',120,'wipes'),
('Johnson''s Baby Lotion 500ml','baby-kids','baby-care','Johnson''s',6900,'bottle',90,'baby,lotion'),
('Johnson''s Baby Shampoo 300ml','baby-kids','baby-care','Johnson''s',5400,'bottle',85,'baby,shampoo'),
('Baby Powder 200g','baby-kids','baby-care','Johnson''s',3900,'piece',110,'baby,powder'),
('Cotton Baby Bibs (Pack of 3)','baby-kids','baby-care','Little Ones',4200,'pack',70,'baby,bibs'),
('Hooded Baby Towel','baby-kids','baby-care','Little Ones',6500,'piece',45,'baby,towel'),
('Soft Stacking Blocks Toy Set','baby-kids','baby-care','Fisher-Price',9800,'pack',35,'baby,toys'),
('Nivea Nourishing Body Lotion 400ml','beauty-cosmetics','skincare','Nivea',7200,'bottle',95,'lotion,skincare'),
('Shea Butter Body Cream 500ml','beauty-cosmetics','skincare','DI CHIES Naturals',6400,'piece',80,'cream,skincare'),
('Neutrogena Face Wash 200ml','beauty-cosmetics','skincare','Neutrogena',9800,'bottle',60,'face wash'),
('Sunscreen SPF 50 100ml','beauty-cosmetics','skincare','Nivea Sun',11500,'bottle',50,'sunscreen'),
('Pure Coconut Body Oil 250ml','beauty-cosmetics','skincare','DI CHIES Naturals',4800,'bottle',85,'oil,skincare'),
('Eau de Parfum Noir 100ml','beauty-cosmetics','fragrance','Maison Noir',42000,'bottle',25,'perfume,premium'),
('Rexona Body Spray 200ml','beauty-cosmetics','fragrance','Rexona',4200,'piece',120,'body spray'),
('Nivea Roll-On Deodorant 50ml','beauty-cosmetics','fragrance','Nivea',3400,'piece',140,'deodorant'),
('Matte Liquid Lipstick','beauty-cosmetics','makeup','Zaron',6500,'piece',70,'lipstick,makeup'),
('Lip Gloss Clear Shine','beauty-cosmetics','makeup','Zaron',4200,'piece',80,'lip gloss'),
('Liquid Foundation 30ml','beauty-cosmetics','makeup','Zaron',9800,'piece',55,'foundation'),
('Loose Setting Powder','beauty-cosmetics','makeup','Zaron',7400,'piece',60,'powder,makeup'),
('Volume Mascara Black','beauty-cosmetics','makeup','House of Tara',5600,'piece',65,'mascara'),
('Precision Eyeliner Pen','beauty-cosmetics','makeup','House of Tara',3900,'piece',75,'eyeliner'),
('Professional Makeup Brush Set (12)','beauty-cosmetics','makeup','House of Tara',18500,'pack',30,'brushes,makeup'),
('Dark & Lovely Shampoo 400ml','beauty-cosmetics','hair-care','Dark & Lovely',6200,'bottle',75,'shampoo'),
('Hair Conditioner 400ml','beauty-cosmetics','hair-care','Dark & Lovely',6400,'bottle',70,'conditioner'),
('Hair Food Cream 250ml','beauty-cosmetics','hair-care','Venus',3800,'piece',95,'hair cream'),
('Heavy Duty Broom','household-essentials','cleaning-tools','HomeCare',2900,'piece',120,'broom,cleaning'),
('Plastic Bucket 20L with Lid','household-essentials','cleaning-tools','HomeCare',5400,'piece',90,'bucket'),
('Spin Mop with Bucket','household-essentials','cleaning-tools','HomeCare',18500,'pack',35,'mop,cleaning'),
('Dustpan & Brush Set','household-essentials','cleaning-tools','HomeCare',2600,'pack',110,'cleaning'),
('Scouring Sponges (Pack of 6)','household-essentials','cleaning-tools','Scotch-Brite',2200,'pack',150,'sponge'),
('Stackable Storage Container 25L','household-essentials','storage','HomeCare',8900,'piece',55,'storage'),
('Clothes Hangers (Pack of 12)','household-essentials','storage','HomeCare',4200,'pack',85,'hangers'),
('Heavy Duty Trash Bags 50s','household-essentials','paper-disposables','Clean Life',3400,'pack',130,'trash bags'),
('Rosies Toilet Tissue 12 Rolls','household-essentials','paper-disposables','Rosies',5200,'pack',140,'tissue'),
('Kitchen Paper Towels 2 Rolls','household-essentials','paper-disposables','Clean Life',2900,'pack',120,'paper towel'),
('Air Freshener Lavender 300ml','household-essentials','paper-disposables','Glade',3800,'piece',100,'air freshener'),
('Oral-B Toothbrush Medium (Pack of 3)','personal-care','oral-care','Oral-B',3900,'pack',150,'toothbrush'),
('Close-Up Toothpaste 140g','personal-care','oral-care','Close-Up',2200,'piece',180,'toothpaste'),
('Colgate Total Toothpaste 100ml','personal-care','oral-care','Colgate',2600,'piece',170,'toothpaste'),
('Listerine Mouthwash 500ml','personal-care','oral-care','Listerine',6900,'bottle',80,'mouthwash'),
('Premier Cool Bath Soap (Pack of 4)','personal-care','bath-body','Premier',3600,'pack',140,'soap'),
('Dettol Shower Gel 250ml','personal-care','bath-body','Dettol',4200,'bottle',110,'shower gel'),
('Gillette Disposable Razors (Pack of 5)','personal-care','shaving-hygiene','Gillette',4800,'pack',95,'razor'),
('Always Ultra Sanitary Pads 8s','personal-care','shaving-hygiene','Always',2400,'pack',180,'sanitary'),
('Ariel Washing Powder 2kg','laundry-cleaning','detergents','Ariel',9600,'pack',90,'detergent'),
('Omo Multi-Active Detergent 900g','laundry-cleaning','detergents','Omo',5200,'pack',120,'detergent'),
('Morning Fresh Dishwashing Liquid 750ml','laundry-cleaning','detergents','Morning Fresh',4400,'bottle',130,'dishwashing'),
('Downy Fabric Softener 1L','laundry-cleaning','detergents','Downy',6800,'bottle',75,'softener'),
('Hypo Bleach 1L','laundry-cleaning','disinfectants','Hypo',1900,'bottle',160,'bleach'),
('Dettol Antiseptic Disinfectant 750ml','laundry-cleaning','disinfectants','Dettol',7400,'bottle',95,'disinfectant'),
('Harpic Toilet Cleaner 500ml','laundry-cleaning','disinfectants','Harpic',3600,'bottle',120,'toilet cleaner'),
('Non-Stick Frying Pan 28cm','kitchen-dining','cookware','Tefal',22500,'piece',30,'cookware,pan'),
('Stainless Steel Cooking Pot 24cm','kitchen-dining','cookware','Master Chef',18900,'piece',35,'cookware,pot'),
('Kitchen Knife Set (5 Pieces)','kitchen-dining','cookware','Master Chef',14500,'pack',40,'knives'),
('Wooden Cooking Spoon Set','kitchen-dining','cookware','Master Chef',3900,'pack',80,'utensils'),
('Porcelain Dinner Plates (Set of 6)','kitchen-dining','tableware','Luminarc',24500,'pack',28,'plates'),
('Glass Tumblers (Set of 6)','kitchen-dining','tableware','Luminarc',12800,'pack',40,'cups,glass'),
('Stainless Steel Cutlery Set (24)','kitchen-dining','tableware','Master Chef',16500,'pack',32,'cutlery'),
('Airtight Food Containers (Set of 5)','kitchen-dining','food-storage','HomeCare',9800,'pack',55,'storage,food'),
('Vacuum Flask 1.5L','kitchen-dining','food-storage','Thermos',13500,'piece',38,'flask'),
('40 Leaves Exercise Books (Pack of 10)','books-stationery','exercise-books','Scholar',3800,'pack',160,'school,books'),
('80 Leaves Exercise Books (Pack of 10)','books-stationery','exercise-books','Scholar',6400,'pack',140,'school,books'),
('A4 Hardcover Notebook','books-stationery','exercise-books','Scholar',2600,'piece',120,'notebook'),
('Bic Ballpoint Pens Blue (Pack of 10)','books-stationery','writing-art','Bic',2400,'pack',200,'pens'),
('HB Pencils (Pack of 12)','books-stationery','writing-art','Staedtler',2100,'pack',180,'pencils'),
('Eraser & Sharpener Set','books-stationery','writing-art','Staedtler',1200,'pack',190,'stationery'),
('Mathematical Set','books-stationery','writing-art','Oxford',3400,'pack',110,'maths,school'),
('Highlighter Markers (Pack of 5)','books-stationery','writing-art','Stabilo',4200,'pack',95,'markers'),
('Scientific Calculator FX-991','books-stationery','school-accessories','Casio',18500,'piece',45,'calculator'),
('School Backpack Large','books-stationery','school-accessories','Trailmate',15900,'piece',50,'bag,school'),
('Insulated Lunch Box','books-stationery','school-accessories','Trailmate',7400,'piece',60,'lunch box'),
('Document File Folders (Pack of 10)','books-stationery','school-accessories','Scholar',3200,'pack',100,'files'),
('Duracell AA Batteries (Pack of 4)','electronics-accessories','power-batteries','Duracell',4200,'pack',150,'batteries'),
('Duracell AAA Batteries (Pack of 4)','electronics-accessories','power-batteries','Duracell',3900,'pack',140,'batteries'),
('4-Way Extension Socket 3m','electronics-accessories','power-batteries','Elite',9800,'piece',60,'extension'),
('20W USB-C Fast Charger','electronics-accessories','power-batteries','Oraimo',12500,'piece',70,'charger'),
('USB-C Charging Cable 1m','electronics-accessories','power-batteries','Oraimo',4800,'piece',120,'cable'),
('LED Bulb 12W E27','electronics-accessories','lighting','Philips',3600,'piece',180,'bulb'),
('Rechargeable LED Lantern','electronics-accessories','lighting','Elite',11500,'piece',45,'lantern'),
('Dog Dry Food Chicken 3kg','pet-supplies','pet-food','Pedigree',18900,'bag',30,'dog,pet food'),
('Cat Dry Food Tuna 2kg','pet-supplies','pet-food','Whiskas',16400,'bag',28,'cat,pet food'),
('Stainless Pet Feeding Bowl','pet-supplies','pet-care','PetLife',5200,'piece',50,'pet,bowl'),
('Pet Shampoo 250ml','pet-supplies','pet-care','PetLife',6100,'bottle',40,'pet,shampoo')
) AS p(name, cat, sub, brand, price, unit, stock, tags)
JOIN public.categories c ON c.slug = p.cat
LEFT JOIN public.subcategories sc ON sc.category_id = c.id AND sc.slug = p.sub;

UPDATE public.products SET image_url = 'https://placehold.co/800x800/f4f4f5/18181b?text=' || replace(replace(name,'&','and'),' ','+'),
  additional_images = ARRAY['https://placehold.co/800x800/ededf0/18181b?text=' || replace(replace(name,'&','and'),' ','+'),
                            'https://placehold.co/800x800/e2e2e6/18181b?text=DI+CHIES'];

WITH ranked AS (SELECT id, row_number() OVER (ORDER BY created_at, name) rn FROM public.products)
UPDATE public.products p SET
  sku = 'DC-' || lpad(r.rn::text, 5, '0'),
  is_popular = (r.rn % 3 = 0),
  is_featured = (r.rn % 7 = 0),
  is_new_arrival = (r.rn % 5 = 0),
  discount_price = CASE WHEN r.rn % 4 = 0 THEN round(p.price * 0.85, 2) ELSE NULL END
FROM ranked r WHERE r.id = p.id;

UPDATE public.products p SET age_restricted = true
FROM public.categories c WHERE c.id = p.category_id AND c.age_restricted;

INSERT INTO public.promotions (title, description, discount_percent, image_url) VALUES
('Month End Grocery Sale','Save on rice, oil and pantry staples until stock lasts.',15,'https://placehold.co/1200x600/18181b/fafafa?text=Month+End+Grocery+Sale'),
('Back to School Bundle','Exercise books, pens and school bags at reduced prices.',10,'https://placehold.co/1200x600/18181b/fafafa?text=Back+to+School'),
('Cellar Selection','Handpicked wines and champagne for the season.',12,'https://placehold.co/1200x600/18181b/fafafa?text=Cellar+Selection'),
('Baby Care Week','Diapers, wipes and formula bundles for new parents.',8,'https://placehold.co/1200x600/18181b/fafafa?text=Baby+Care+Week');
-- Verification
SELECT
  (SELECT count(*) FROM public.categories) AS categories,
  (SELECT count(*) FROM public.subcategories) AS subcategories,
  (SELECT count(*) FROM public.products) AS products,
  (SELECT count(*) FROM public.promotions) AS promotions;
